### ISSUE TITLE
TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-desktop#1031]
**What version of WebTorrent Desktop?** 0.17.2

**What operating system and version?** Mac, Windows

From our telemetry error logs, we picked up this error. It occurred 6 times today.

```
Processes: window, platforms: darwin win32, versions: 0.17.1 0.17.2
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.parse (path.js:1496:5)
    at TorrentListController.saveTorrentFileAs (.../build/renderer/controllers/torrent-list-controller.js:239:28)
    at saveTorrentFileAs (.../build/renderer/main.js:239:81)
    at dispatch (.../build/renderer/main.js:319:26)
    at dispatch (.../build/renderer/lib/dispatcher.js:18:13)
    at click (.../build/renderer/controllers/torrent-list-controller.js:227:35)
    at CallbacksRegistry.apply (/Applications/WebTorrent.app/Contents/Resources/electron.asar/common/api/callbacks-registry.js:54:39)
    at EventEmitter.<anonymous> (/Applications/WebTorrent.app/Contents/Resources/electron.asar/renderer/api/remote.js:282:21)
    at emitThree (events.js:116:13)
```

**Comment by Goldob** [comment]
How to reproduce:

1. Disable internet connection.
2. Add a new torrent by magnet link.
3. Right click it, then _Save Torrent File As..._

The problem is that we are able to generate a torrent file only after we download all the metadata, which magnet links don't contain.

**Comment by feross** [comment]
@Goldob Nice work tracking this down. Makes a lot of sense.
