### ISSUE TITLE
Linux ZIP package: pushd is not in default shell (/bin/sh) path

### ISSUE THREAD

**Issue by grunjol** [feross/webtorrent-desktop#265]
`pushd` command is not in $PATH in `/bin/sh` which is the default shell for `child_process.execSync` module 

`Packaging app for platform linux x64 using electron v0.37.2`

`/bin/sh: 1: pushd: not found
child_process.js:507
    throw err;`

`Error: Command failed: pushd /home/grunjol/workspaces/wt/webtorrent-desktop/dist && zip -r -y /home/grunjol/workspaces/wt/webtorrent-desktop/dist/WebTorrent-v0.1.1-linux.zip WebTorrent-linux-x64 && popd
/bin/sh: 1: pushd: not found`

`    at checkExecSyncError (child_process.js:464:13)
    at Object.execSync (child_process.js:504:13)
    at /home/grunjol/workspaces/wt/webtorrent-desktop/bin/package.js:296:8
    at /home/grunjol/workspaces/wt/webtorrent-desktop/node_modules/electron-packager/index.js:213:7
    at end (/home/grunjol/workspaces/wt/webtorrent-desktop/node_modules/electron-packager/node_modules/run-series/index.js:8:15)
    at done (/home/grunjol/workspaces/wt/webtorrent-desktop/node_modules/electron-packager/node_modules/run-series/index.js:11:10)
    at each (/home/grunjol/workspaces/wt/webtorrent-desktop/node_modules/electron-packager/node_modules/run-series/index.js:16:43)
    at /home/grunjol/workspaces/wt/webtorrent-desktop/node_modules/electron-packager/common.js:155:7
    at next (/home/grunjol/workspaces/wt/webtorrent-desktop/node_modules/rimraf/rimraf.js:74:7)
    at FSReqWrap.CB [as oncomplete] (/home/grunjol/workspaces/wt/webtorrent-desktop/node_modules/rimraf/rimraf.js:110:9)
`

* OS: Ubuntu Linux 15.10
* WTD version: 0.1.1

**Comment by dcposch** [comment]
We can probably fix this by changing the shell from `sh` to `bash`

Shell scripts are the jankiest thing

**Comment by dcposch** [comment]
Actually, we can just use `cd`, right? I don't think we need the `popd` at the end
