### ISSUE TITLE
Tray icon fails to quit the app

### ISSUE THREAD

**Issue by feross** [feross/webtorrent-desktop#288]
https://ncry.pt/p/mNBn#Kwf7wV3m9t4mXgTxjzZiAGjoFkHv9fVkq5Cpjvk9FLk

**Comment by jercos** [comment]
That paste is actually set to expire in a week, so for posterity... on trying to quit the app under Linux.

```
Uncaught Exception:
TypeError: e.preventDefault is not a function
    at quitApp (/home/user/webtorrent-desktop/main/tray.js:55:5)
    at MenuItem.click (/home/user/webtorrent-desktop/node_modules/electron-prebuilt/dist/resources/electron.asar/browser/api/menu-item.js:81:16)
    at Function.delegate.executeCommand (/home/user/webtorrent-desktop/node_modules/electron-prebuilt/dist/resources/electron.asar/browser/api/menu.js:119:40)
```

**Comment by feross** [comment]
Working on this

**Comment by feross** [comment]
This is fixed on `master` now :)
