### ISSUE TITLE
Cannot create BrowserWindow before app is ready

### ISSUE THREAD

**Issue by montanaflynn** [feross/webtorrent-desktop#524]
Just saw this pop up in an error modal box:

```
Uncaught Exception:
Error: Cannot create BrowserWindow before app is ready
    at Error (native)
    at Object.createMainWindow (/Applications/WebTorrent.app/Contents/Resources/app.asar/main/windows.js:91:28)
    at EventEmitter.<anonymous> (/Applications/WebTorrent.app/Contents/Resources/app.asar/main/index.js:86:13)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)

**Comment by feross** [comment]
Thanks for the report -- this is fixed now. Will go out in the next release.
