### ISSUE TITLE
Wrong file order due to sorting

### ISSUE THREAD

**Issue by demoneaux** [feross/webtorrent-desktop#591]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
feross/webtorrent-desktop@7de3d3c

**What operating system and version?**
Windows 10

**What did you do?**
I opened a video by pressing play on the torrent list.

**What did you expect to happen?**
Video plays.

**What actually happened?**
A grey screen shows up with the following error:
```
rendering error: Cannot read property 'length' of undefined
	TypeError: Cannot read property 'length' of undefined
    at renderMedia (C:\Users\weeseng\Documents\GitHub\webtorrent-desktop\renderer\views\player.js:64:31)
    at Object.Player (C:\Users\weeseng\Documents\GitHub\webtorrent-desktop\renderer\views\player.js:24:21)
    at getView (C:\Users\weeseng\Documents\GitHub\webtorrent-desktop\renderer\views\app.js:82:20)
    at App (C:\Users\weeseng\Documents\GitHub\webtorrent-desktop\renderer\views\app.js:45:30)
    at render (file:///C:/Users/weeseng/Documents/GitHub/webtorrent-desktop/renderer/index.js:186:12)
    at redraw (C:\Users\weeseng\Documents\GitHub\webtorrent-desktop\node_modules\main-loop\index.js:65:23)
    at C:\Users\weeseng\Documents\GitHub\webtorrent-desktop\node_modules\raf\index.js:72:10
```

Seems like there is an error when there are no subtitle tracks.

**Comment by demoneaux** [comment]
Hmm,  I also see:
```
[...]\webtorrent-desktop\node_modules\raf\index.js:74 Uncaught TypeError: Cannot read property 'ownerDocument' of null
```

**Comment by demoneaux** [comment]
I think I've figured this out. I was upgrading from an older version of WebTorrent and ran into this as files are now sorted (https://github.com/feross/webtorrent-desktop/commit/fc9a73d67f76c5884f678374e305c32f40e32ece), but the `defaultFilePlayIndex` is not changed.

**Comment by demoneaux** [comment]
This seems like a pretty serious issue. Maybe file sorting should be disabled?

**Comment by demoneaux** [comment]
Maybe you should recommend that users remove all their older torrents? Since they won't work very well.

**Comment by feross** [comment]
@demoneaux The fix of deleting the `files` field should do the trick. :)
