### ISSUE TITLE
Blank screen on windows 10

### ISSUE THREAD

**Issue by timmiboy** [feross/webtorrent-desktop#676]
**What version of WebTorrent Desktop?** (See the 'About WebTorrent' menu)
v0.8.0

**What operating system and version?**
Windows 10
**What did you do?**
Play sample videos

**What did you expect to happen?**
video playback

**What actually happened?**
blank screen

Here is an error output from the console:

rendering error: Cannot read property 'false' of undefined
	TypeError: Cannot read property 'false' of undefined
    at C:\Users\***\AppData\Local\WebTorrent\app-0.8.0\resources\app.asar\renderer\views\player.js:439:43
    at Array.forEach (native)
    at renderPlayerControls (C:\Users\***\AppData\Local\WebTorrent\app-0.8.0\resources\app.asar\renderer\views\player.js:418:13)
    at Object.Player (C:\Users\***\AppData\Local\WebTorrent\app-0.8.0\resources\app.asar\renderer\views\player.js:22:9)
    at getView (C:\Users\***\AppData\Local\WebTorrent\app-0.8.0\resources\app.asar\renderer\views\app.js:81:20)
    at App (C:\Users\****\AppData\Local\WebTorrent\app-0.8.0\resources\app.asar\renderer\views\app.js:44:30)
    at render (file:///C:/Users/***/AppData/Local/WebTorrent/app-0.8.0/resources/app.asar/renderer/main.js:126:12)
    at redraw (C:\Users\***\AppData\Local\WebTorrent\app-0.8.0\resources\app.asar\node_modules\main-loop\index.js:65:23)
    at C:\Users\***\AppData\Local\WebTorrent\app-0.8.0\resources\app.asar\node_modules\raf\index.js:72:10

**Comment by timmiboy** [comment]
File: main.js line 128

**Comment by timmiboy** [comment]
Another error. Got the sample file to work once. Now its blank again:

C:\Users\**\AppData\Local\WebTorrent\app-0.8.0\resources\app.asar\node_modules\raf\index.js:74 Uncaught TypeError: Cannot read property 'ownerDocument' of null

**Comment by Goldob** [comment]
Already fixed that, awaiting merge at #673.

**Comment by timmiboy** [comment]
which branch has the fix?

**Comment by Goldob** [comment]
It's the brach `fix/player` on my forked repository.

https://github.com/Goldob/webtorrent-desktop

You should rather wait until it is merged unless you want to test it.

**Comment by mathiasvr** [comment]
Fixed and released as `v0.8.1`
