### ISSUE TITLE
Common error: Cannot read property 'getHostNode' of null

### ISSUE THREAD

**Issue by dcposch** [feross/webtorrent-desktop#800]
```
TypeError: Cannot read property 'getHostNode' of null
    at Object.getHostNode (...\node_modules\react\lib\ReactReconciler.js:64:28)
    at ReactCompositeComponentWrapper.getHostNode (...\node_modules\react\lib\ReactCompositeComponent.js:397:28)
    at Object.getHostNode (...\node_modules\react\lib\ReactReconciler.js:64:29)
    at Object.updateChildren (...\node_modules\react\lib\ReactChildReconciler.js:114:48)
    at ReactDOMComponent._reconcilerUpdateChildren (...\node_modules\react\lib\ReactMultiChild.js:215:28)
    at ReactDOMComponent._updateChildren (...\node_modules\react\lib\R
```

**Comment by feross** [comment]
This just means that we have an uncaught exception in a React component. I think this exception always happens AFTER another exception. So it can be safely ignored and will go away once we fix the root cause exception.
