### ISSUE TITLE
Common error: Cannot read property 'removeListener' of null

### ISSUE THREAD

**Issue by dcposch** [feross/webtorrent-desktop#890]
```
Processes: webtorrent, platforms: darwin linux win32, versions: pre-0.12 0.13.1
TypeError: Cannot read property 'removeListener' of null
    at Server.server.close (...\node_modules\webtorrent\lib\server.js:29:14)
    at Server.server.destroy (...\node_modules\webtorrent\lib\server.js:41:17)
    at ...\node_modules\webtorrent\lib\torrent.js:661:14
    at ...\node_modules\run-parallel\index.js:41:7
    at Array.forEach (native)
    at module.exports (...\node_modules\run-parallel\index.js:40:11)
    at Torrent._destroy (...\node_modules\webtorrent\lib\torrent.js:677:3)
    at Torrent.destroy (...\node_modules\webtorrent\lib\torrent.js:630:8)
    at stopTorrenting (...\build\renderer\webtorrent.js:109:24)
    at EventEmitter.ipc.on (...\build\renderer\webtorrent.js:70:49)
```

**Comment by dcposch** [comment]
Fixed in the library, will be fixed in the next release of the app
