### ISSUE TITLE
Common error: Cannot read property 'files' of null

### ISSUE THREAD

**Issue by dcposch** [feross/webtorrent-desktop#891]
```
Processes: webtorrent, platforms: darwin linux win32, versions: 0.13.1
TypeError: Cannot read property 'files' of null
    at selectFiles (...\build\renderer\webtorrent.js:343:36)
    at EventEmitter.ipc.on (...\build\renderer\webtorrent.js:77:58)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

**Comment by dcposch** [comment]
### How to reproduce
* Expand any torrent that's not currently active (not downloading or seeding, eg one of the default torrents on a fresh install)
* Click X next to any file
